/* DO NOT EDIT. GENERATED BY enum_with_string.py ReverseComplementFor
 * ReverseComplementFor_undefined for_reference for_reference_canonical
 * for_query */
#ifndef REVERSE_COMPLEMENT_FOR_HPP
#define REVERSE_COMPLEMENT_FOR_HPP

#include <cstddef>
#include <string>
#include <vector>
#include <cassert>

enum EnumReverseComplementFor
{
  ReverseComplementFor_undefined,
  for_reference,
  for_reference_canonical,
  for_query
};

class ReverseComplementFor
{
  static constexpr const char *string_values[] = {
      "reversecomplementfor_undefined", "for_reference",
      "for_reference_canonical", "for_query"};
  static constexpr const size_t num_values =
      sizeof string_values / sizeof string_values[0];
  EnumReverseComplementFor value;

 public:
  ReverseComplementFor(void) : value(ReverseComplementFor_undefined) {}
  std::string string_values_joined(const char *sep,
                                   size_t start_index = 1) const noexcept
  {
    assert(start_index < num_values);
    std::string out_string{string_values[start_index]};
    for (size_t idx = start_index + 1; idx < num_values; idx++)
    {
      out_string += std::string(sep) + std::string(string_values[idx]);
    }
    return out_string;
  }
  void set(const std::string &str, size_t start_index = 1)
  {
    size_t idx;
    for (idx = 0; idx < num_values; idx++)
    {
      if (str == std::string(string_values[idx]))
      {
        value = static_cast<EnumReverseComplementFor>(idx);
        break;
      }
    }
    if (idx == num_values)
    {
      throw std::runtime_error(std::string("illegal argument ") + str +
                               std::string(", possible values are: ") +
                               string_values_joined(", ", start_index));
    }
  }
  bool is(EnumReverseComplementFor param) const noexcept
  {
    return value == param;
  }
  std::string str(void) const noexcept
  {
    assert(static_cast<size_t>(value) < num_values);
    return string_values[static_cast<size_t>(value)];
  }
  std::vector<std::string> string_values_get(void) const noexcept
  {
    std::vector<std::string> vec_s{};
    for (size_t idx = 0; idx < num_values; idx++)
    {
      vec_s.push_back(string_values[idx]);
    }
    return vec_s;
  }
};
#endif
